const actionTypes = {
  LOGIN: "LOGIN",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGOUT: "LOGOUT",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",

  GET_POSTS: "GET_POSTS",
  GET_POSTS_LIMIT: "GET_POSTS_LIMIT",
  GET_NEW_POSTS: "GET_NEW_POSTS",
  EDIT_DATA: "EDIT_DATA",
  RESET_DATAEDIT: "RESET_DATAEDIT",

  GET_CATEGORIES: "GET_CATEGORIES",

  GET_PRICES: "GET_PRICES",

  GET_AREAS: "GET_AREAS",

  GET_PROVINCES: "GET_PROVINCES",

  GET_POSTS_ADMIN: "GET_POSTS_ADMIN",

  //USER
  GET_CURRENT: "GET_CURRENT",
  GET_ALL_USER: "GET_ALL_USER",
};

export default actionTypes;
